DROP TABLE IF EXISTS meals;
CREATE TABLE meals (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    team TEXT NOT NULL UNIQUE,
    city TEXT NOT NULL,
    sport TEXT NOT NULL,
    league TEXT NOT NULL,
    games INTEGER DEFAULT 0,
    wins INTEGER DEFAULT 0,
    deleted BOOLEAN DEFAULT FALSE
);