DROP TABLE IF EXISTS teams;
CREATE TABLE teams (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    team TEXT NOT NULL UNIQUE,
    nfl_id INTEGER NOT NULL,
    loc TEXT NOT NULL,
    games INTEGER DEFAULT 0,
    wins INTEGER DEFAULT 0,
    favorite BOOLEAN DEFAULT FALSE
);
